# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# stdlib
from re import findall

# Zato
from zato_testing.service import Service

# ################################################################################################################################
# ################################################################################################################################

class NotGiven:
    pass

# ################################################################################################################################
# ################################################################################################################################

class RESTAdapterResponse:
    def __init__(self, data, raw_response):
        self.data = data
        self.raw_response = raw_response

# ################################################################################################################################
# ################################################################################################################################

def cast_(type_hint, value):
    return value

# ################################################################################################################################
# ################################################################################################################################

class RESTAdapter(Service):

    # These may be overridden by individual subclasses
    model            = None
    conn_name        = ''
    auth_scopes      = ''
    sec_def_name     = None
    log_response     = False
    map_response     = None
    get_conn_name    = None
    get_auth_scopes  = None
    get_path_params  = None
    get_method       = None
    get_request      = None
    get_headers      = None
    get_query_string = None
    get_auth_bearer  = None
    get_sec_def_name = None
    needs_raw_response = False

    max_retries        = 0
    retry_sleep_time   = 2
    retry_backoff_threshold = 3
    retry_backoff_multiplier = 2

    has_query_string_id   = False
    query_string_id_param = None

    has_json_id   = False
    json_id_param = None

    # Default to GET calls
    method = 'GET'

# ################################################################################################################################

    def rest_call(
        self,
        conn_name,     # type: str
        *,
        data='',       # type: ignore
        model=None,    # type: modelnone
        callback=None, # type: callnone
        params=None,   # type: strdictnone
        headers=None,  # type: strdictnone
        method='',     # type: str
        sec_def_name=None, # type: any_
        auth_scopes=None,  # type: any_
        log_response=True, # type: bool
    ):
        # Type checks
        data:'any_'
        raw_response:'any_'

        # Get the actual REST connection ..
        conn:'RESTWrapper' = self.out.rest[conn_name].conn

        # .. invoke the system and map its response back through the callback callable ..
        response = conn.rest_call(
            cid=self.cid,
            data=data,
            model=model, # type: ignore
            callback=callback,
            params=params,
            headers=headers,
            method=method,
            sec_def_name=sec_def_name,
            auth_scopes=auth_scopes,
            log_response=log_response,
            max_retries=self.max_retries,
            retry_sleep_time=self.retry_sleep_time,
            retry_backoff_threshold=self.retry_backoff_threshold,
        )

        if response is not None:
            data, raw_response = response

            # .. and return the result to our caller, optionally returning the raw response as well ..
            if self.needs_raw_response:
                return RESTAdapterResponse(data, raw_response)
            else:
                return data

# ################################################################################################################################

    def handle(self):

        # Local aliases
        params:'strdict' = {}
        request:'any_' = ''
        headers:'strstrdict' = {}

        # The outgoing connection to use may be static or dynamically generated
        if self.get_conn_name:
            conn_name = self.get_conn_name
        else:
            conn_name = self.conn_name

        # The request to use may be dynamically generated
        if self.get_request:
            request = self.get_request() # type: ignore

        #
        # Build our query parameters, which can be partly implicit if this is an ID-only service
        # or explicitly if we have a method to do so.
        #
        if self.has_query_string_id:

            if self.query_string_id_param:
                query_string_id_param = self.query_string_id_param
            else:
                query_string_id_param = 'id'

            params[query_string_id_param] = self.request.input[query_string_id_param]

        # Update the query string with information obtained earlier
        if self.get_query_string:
            _params:'strdict' = self.get_query_string(params)
            params.update(_params)

        # Obtain any possible path parameters
        if self.get_path_params:
            _params:'strdict' = self.get_path_params(params)
            params.update(_params)

        # The REST method may be dynamically generated
        if self.get_method:
            method:'str' = self.get_method()
        else:
            method = self.method

        # Uppercase the method per what HTTP expects
        method = method.upper()

        # Authentication bearer token may be dynamically generated
        if self.get_auth_bearer:
            token:'str' = self.get_auth_bearer()
            headers['Authorization'] = f'Bearer {token}'

        # Security definition can be dynamically generated ..
        if self.get_sec_def_name:
            sec_def_name = self.get_sec_def_name()

        # .. it may also have been given explicitly ..
        elif self.sec_def_name:
            sec_def_name = self.sec_def_name

        # .. otherwise, we will indicate explicitly that it was not given on input in any way.
        else:
            sec_def_name = NotGiven

        # Auth scopes can be dynamically generated ..
        if self.get_auth_scopes:
            auth_scopes = self.get_auth_scopes()

        # .. it may also have been given explicitly ..
        elif self.auth_scopes:
            auth_scopes = self.auth_scopes

        # .. otherwise, we will indicate explicitly that they were not given on input in any way.
        else:
            auth_scopes = ''

        # Headers may be dynamically generated
        if self.get_headers:
            _headers:'strstrdict' = self.get_headers()
            headers.update(_headers)

        # Obtain the result ..
        out = self.rest_call(
            conn_name,
            data=request,
            model=self.model,
            callback=self.map_response,
            params=params,
            headers=headers,
            method=method,
            sec_def_name=sec_def_name,
            auth_scopes=auth_scopes,
            log_response=self.log_response,
        )

        # .. and return it to our caller.
        self.response.payload = out


SOAPAdapter = RESTAdapter

# ################################################################################################################################
# ################################################################################################################################

class BusinessCentralAdapter(Service):

    model     = None
    conn_name = cast_('str', None)
    base_url  = cast_('str', None)
    endpoint  = cast_('str', None)

# ################################################################################################################################

    def _find_placeholders(self, text:'str', pattern:'str'=r'\{([^{}]+)\}') -> 'strlist':
        matches = findall(pattern, text)
        return matches

# ################################################################################################################################

    def _replace_placeholders_by_input(self, text:'str', placeholders:'strlist') -> 'str':

        # Local variables
        found = {}

        # We go here if we don't have any input at all
        if not self.request.raw_request:
            missing = placeholders
        else:

            missing = []

            for item in placeholders:
                if item in self.request.raw_request:
                    value = self.request.raw_request[item]
                    value = str(value)
                    found[item] = value
                else:
                    missing.append(item)

        # Report any missing input elements
        if missing:
            suffix = 's ' if len(missing) > 1 else ' '
            raise Exception(f'Element{suffix}missing on input -> `{sorted(missing)}` ')

        for name, value in found.items():
            pattern = '{' + name + '}'
            text = text.replace(pattern, value)

        return text

# ################################################################################################################################

    def _replace_placeholders_by_file(self, text:'str', placeholder:'str') -> 'str':

        # Extrac the config file's name ..
        file_name, path = placeholder.split(':')
        file_base = file_name.split('.')[0]

        # .. and the path in that file leading to our value ..
        path = path.split('.')

        # .. get the actual config file now ..
        config = self.config[file_base]

        # .. we're going to traverse that element ..
        value = config

        # .. keep traversing until we've run out of the path elements ..
        while path:
            elem = path.pop(0)
            try:
                value = value[elem]
            except KeyError:
                raise Exception(f'Key not found -> `{placeholder}` -> `{elem}` in `{sorted(value)}`')

        # .. finally, we can return our value to the caller.
        return value

# ################################################################################################################################

    def _replace_placeholders(self, text:'str') -> 'str':

        # Find all the placeholders to replace ..
        placeholders = self._find_placeholders(text)

        # .. if there are none, we can return early ..
        if not placeholders:
            return text

        # .. we go here if we need to wait a value in a config file ..
        if ':' in text:
            return self._replace_placeholders_by_file(text, placeholders[0])

        # .. or we go here if we need to wait a value or values on input.
        else:
            return self._replace_placeholders_by_input(text, placeholders)

# ################################################################################################################################

    def get_model(self) -> 'any_':
        # Don't return anything by default because models are optional
        pass

# ################################################################################################################################

    def get_conn_name(self) -> 'str':
        raise NotImplementedError('Must be implemented by subclasses')

# ################################################################################################################################

    def get_base_url(self) -> 'str':
        raise NotImplementedError('Must be implemented by subclasses')

# ################################################################################################################################

    def _invoke_business_central(self, endpoint:'str', base_url:'str | None') -> 'anydictnone':

        # Get our configurarion
        model = self.model or self.get_model()
        conn_name = self.conn_name or self.get_conn_name()
        base_url = base_url or self.get_base_url()

        # Build a full address ..
        address_full = f'{base_url}/{endpoint}'

        # .. get the connection ..
        conn = self.cloud.ms365.get(conn_name).conn # type: ignore

        # .. obtain a new client ..
        with conn.client() as client:

            # .. make sure our access token is fresh ..
            client.refresh()

            # .. make the request ..
            response = client.impl.connection.get(address_full)

            # .. do we have a 200 OK ..
            if response.status_code == OK:

                # .. if yes, we can extract our response ..
                data = response.json()

                # .. if we have a model ..
                if model:

                    # .. is the response a list of values ..
                    list_value = data.get('value', NOT_GIVEN)

                    # .. try to extract all the objects if we actually have a list ..
                    if isinstance(list_value, list):
                        _model_data = []
                        for item in list_value:
                            _model = model.from_dict(item)
                            _model_data.append(_model)

                    # .. or we can map the response as is ..
                    else:
                        _model_data = model.from_dict(data)

                    # .. map the result to the object we're returning ..
                    data = _model_data

                # .. now, we can return the result to the caller.
                return data

            # .. otherwise, raise an exception.
            else:
                msg = f'Endpoint invocation error ({response.status_code}) -> {response.text}'
                raise Exception(msg)

# ################################################################################################################################

    def handle(self):

        endpoint = self._replace_placeholders(self.endpoint)
        base_url = self._replace_placeholders(self.base_url)

        self.response.payload = self._invoke_business_central(endpoint, base_url)
