# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# stdlib
from http.client import BAD_REQUEST, CONFLICT, FORBIDDEN, INTERNAL_SERVER_ERROR, METHOD_NOT_ALLOWED, NOT_FOUND, \
     SERVICE_UNAVAILABLE, UNAUTHORIZED

# ################################################################################################################################
# ################################################################################################################################

TOO_MANY_REQUESTS = 429

HTTP_RESPONSES = {
    BAD_REQUEST: 'Bad Request',
    CONFLICT: 'Conflict',
    FORBIDDEN: 'Forbidden',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    METHOD_NOT_ALLOWED: 'Method Not Allowed',
    NOT_FOUND: 'Not Found',
    SERVICE_UNAVAILABLE: 'Service Unavailable',
    UNAUTHORIZED: 'Unauthorized',
    TOO_MANY_REQUESTS: 'Too Many Requests',
}

# ################################################################################################################################
# ################################################################################################################################

class ZatoException(Exception):
    """ Base class for all Zato custom exceptions.
    """
    def __init__(self, cid=None, msg=None):
        super(ZatoException, self).__init__(msg)
        self.cid = cid
        self.msg = msg

    def __repr__(self):
        return '<{} at {} cid:`{}`, msg:`{}`>'.format(
            self.__class__.__name__, hex(id(self)), self.cid, self.msg)

    __str__ = __repr__

# ################################################################################################################################

class StatusAwareException(ZatoException):
    """ Raised when the underlying error condition can be easily expressed
    as one of the HTTP status codes.
    """
    def __init__(self, cid, msg, status, needs_msg=False):
        super(StatusAwareException, self).__init__(cid, msg)
        self.status = status
        self.reason = HTTP_RESPONSES[status]
        self.needs_msg = needs_msg

    def __repr__(self):
        return '<{} at {} cid:`{}`, status:`{}`, msg:`{}`>'.format(
            self.__class__.__name__, hex(id(self)), self.cid, self.status, self.msg)

# ################################################################################################################################

class HTTPException(StatusAwareException):
    pass

# ################################################################################################################################

class Inactive(ZatoException):
    """ Raised when an attempt was made to use an inactive resource, such
    as an outgoing connection or a channel.
    """
    def __init__(self, name):
        super(Inactive, self).__init__(None, '`{}` is inactive'.format(name))

# ################################################################################################################################

class Reportable(HTTPException):
    def __init__(self, cid, msg, status, needs_msg=False):
        super(ClientHTTPError, self).__init__(cid, msg, status, needs_msg)

# ################################################################################################################################

class BadRequest(Reportable):
    def __init__(self, cid, msg='Bad request', needs_msg=False):
        super(BadRequest, self).__init__(cid, msg, BAD_REQUEST, needs_msg)

# ################################################################################################################################

class Conflict(Reportable):
    def __init__(self, cid, msg):
        super(Conflict, self).__init__(cid, msg, CONFLICT)

# ################################################################################################################################

class Forbidden(Reportable):
    def __init__(self, cid, msg='You are not allowed to access this resource', *ignored_args, **ignored_kwargs):
        super(Forbidden, self).__init__(cid, msg, FORBIDDEN)

# ################################################################################################################################

class MethodNotAllowed(Reportable):
    def __init__(self, cid, msg):
        super(MethodNotAllowed, self).__init__(cid, msg, METHOD_NOT_ALLOWED)

# ################################################################################################################################

class NotFound(Reportable):
    def __init__(self, cid, msg):
        super(NotFound, self).__init__(cid, msg, NOT_FOUND)

# ################################################################################################################################

class Unauthorized(Reportable):
    def __init__(self, cid, msg, challenge):
        super(Unauthorized, self).__init__(cid, msg, UNAUTHORIZED)
        self.challenge = challenge

# ################################################################################################################################

class TooManyRequests(Reportable):
    def __init__(self, cid, msg):
        super(TooManyRequests, self).__init__(cid, msg, TOO_MANY_REQUESTS)

# ################################################################################################################################

class InternalServerError(Reportable):
    def __init__(self, cid, msg='Internal server error'):
        super(InternalServerError, self).__init__(cid, msg, INTERNAL_SERVER_ERROR)

# ################################################################################################################################

class ServiceUnavailable(Reportable):
    def __init__(self, cid, msg):
        super(ServiceUnavailable, self).__init__(cid, msg, SERVICE_UNAVAILABLE)

# ################################################################################################################################

