# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# stdlib
from dataclasses import asdict, fields as dataclass_fields
from traceback import extract_stack

# ################################################################################################################################
# ################################################################################################################################

_FIELDS = '__dataclass_fields__'

class BackendInvocationError(Exception):
    def __init__(self, cid, msg, needs_msg=False):
        self.cid = cid
        self.msg = msg
        self.needs_msg = needs_msg
        super().__init__(msg)

class BaseModel:
    pass

class MarshalAPI:
    def from_dict(self, service, data, class_, extra=None):
        instance = class_()
        if isinstance(data, dict):
            for key, value in data.items():
                if hasattr(instance, key):
                    setattr(instance, key, value)
        return instance

def cast_(type_hint, value):
    return value

try:
    from orjson import dumps
except ImportError:
    from json import dumps as _dumps
    def dumps(obj, default=None, option=0):
        return _dumps(obj, default=default)

try:
    from bson import ObjectId
except ImportError:
    class ObjectId:
        pass

# ################################################################################################################################
# ################################################################################################################################

class Model(BaseModel):
    __name__: 'str'
    after_created = None

    def __getitem__(self, name, default=None):
        if not isinstance(name, str):
            name = str(name)
        return getattr(self, name, default)

    def __contains__(self, name):
        return hasattr(self, name)

    def get(self, name):
        return self.__getitem__(name)

    @classmethod
    def zato_get_fields(class_:'any_') -> 'anydict':
        fields = getattr(class_, _FIELDS) # type: anydict
        return fields

    @classmethod
    def _zato_from_dict(class_, data, extra=None):
        api = MarshalAPI()
        return api.from_dict(cast_('Service', None), data, class_, extra=extra)

    from_dict = _zato_from_dict

    def to_dict(self):
        try:
            return asdict(self)
        except TypeError as e:
            if 'asdict() should be called on dataclass instances' in str(e):
                stack = extract_stack()

                for frame in reversed(stack):
                    if '/opt/' in frame.filename and '/zato/' not in frame.filename:
                        line_len = len(frame.line)
                        msg = f'Class {self.__class__.__name__} is not a dataclass. Add "@dataclass(init=False)" so it looks like below:\n\n'
                        msg += f'@dataclass(init=False)\n'
                        msg += f'class {self.__class__.__name__}(Model):\n'
                        msg += f'  ..\n\n'
                        msg += f'File "{frame.filename}", line {frame.lineno}, in {frame.name}\n'
                        msg += f'  {frame.line}\n'
                        msg += f'  {"^" * line_len}'
                        break
                else:
                    msg = f'Class {self.__class__.__name__} is not a dataclass. Add "@dataclass(init=False)" so it looks like below:\n\n'
                    msg += f'@dataclass(init=False)\n'
                    msg += f'class {self.__class__.__name__}(Model):\n'
                    msg += f'  ..'

                raise BackendInvocationError(
                    None,
                    msg,
                    needs_msg=True
                )
            else:
                raise

    def _json_default_serializer(self, value):

        # Serialize BSON / MongoDB objects
        if isinstance(value, ObjectId):
            return str(value)

        elif isinstance(value, bytes):
            return value.decode('utf8')

        # We do not know how to serialize it
        return value

    def to_json(self, default=None, impl_extra=0):
        return dumps(self, default=default or self._json_default_serializer, option=impl_extra)

    def clone(self) -> 'any_':
        data = self.to_dict()
        out = self.__class__._zato_from_dict(None, data)
        return out

    @staticmethod
    def build_model_from_flat_input(
        server,            # type: ParallelServer
        sio_server_config, # type: ignore
        _CySimpleIO,       # type: ignore
        name,  # type: str
        input, # type: str | tuplist
    ) -> 'type_[BaseModel]':

        # Local imports
        from zato.simpleio import is_sio_bool, is_sio_int

        # Local aliases
        model_fields = []

        # Make sure this is a list-like container ..
        if isinstance(input, str):
            input = [input]

        # .. build an actual SIO handler ..
        _cy_simple_io = _CySimpleIO(server, sio_server_config, input) # type: ignore

        # .. now, go through everything we have on input ..
        for item in input:

            # .. find out if this is a required element or not ..
            is_optional = item.startswith('-')
            is_required = not is_optional

            # .. turn each element input into a Cython-based one ..
            sio_elem = _cy_simple_io.convert_to_elem_instance(item, is_required) # type: ignore

            # .. check if it is not a string ..
            is_int:'bool'  = is_sio_int(sio_elem)
            is_bool:'bool' = is_sio_bool(sio_elem)

            # .. turn the type into a model-compatible name ..
            if is_int:
                _model_type = int
            elif is_bool:
                _model_type = bool
            else:
                _model_type = str

            # .. append a model-compatible definition of this field for later use ..
            model_fields.append((sio_elem.name, _model_type))

        model = make_dataclass(name, model_fields, bases=(Model,))
        return model # type: ignore


# ################################################################################################################################
# ################################################################################################################################
