# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# Zato
from zato_testing.bunch import Bunch

# ################################################################################################################################
# ################################################################################################################################

def cast_(type_hint, value):
    return value

# ################################################################################################################################
# ################################################################################################################################

class ServiceInput(Bunch):
    pass

class Logger:
    def info(self, *args, **kwargs): pass
    def warning(self, *args, **kwargs): pass
    def error(self, *args, **kwargs): pass
    def debug(self, *args, **kwargs): pass

# ################################################################################################################################
# ################################################################################################################################

class HTTPRequestData:
    """ Data regarding an HTTP request.
    """
    __slots__ = 'method', 'GET', 'POST', 'path', 'params', 'user_agent', 'headers', '_wsgi_environ'

    def __init__(self, _Bunch=Bunch):
        self.method = None # type: str
        self.GET = _Bunch()
        self.POST = _Bunch()
        self.path = None # type: str
        self.params = _Bunch()
        self.user_agent = ''
        self.headers = _Bunch()
        self._wsgi_environ = None # type: dict

    def init(self, wsgi_environ=None):
        self._wsgi_environ = wsgi_environ or {}
        self.method = wsgi_environ.get('REQUEST_METHOD') # type: str
        self.GET.update(wsgi_environ.get('zato.http.GET', {})) # type: dict
        self.POST.update(wsgi_environ.get('zato.http.POST', {}))
        self.path = wsgi_environ.get('PATH_INFO') # type: str
        self.params.update(wsgi_environ.get('zato.http.path_params', {}))
        self.user_agent = wsgi_environ.get('HTTP_USER_AGENT')
        self._extract_headers()

    def _extract_headers(self):
        for key, value in self._wsgi_environ.items():
            if key.startswith('HTTP_'):
                header_name = key[5:].replace('_', '-').lower()
                self.headers[header_name] = value

    def get_form_data(self) -> 'stranydict':
        return util_get_form_data(self._wsgi_environ)

    def __repr__(self):
        return make_repr(self)

    def to_dict(self) -> 'stranydict':
        return {
            'method': self.method,
            'GET': dict(self.GET),
            'POST': dict(self.POST),
            'path': self.path,
            'params': dict(self.params),
            'user_agent': self.user_agent,
            'headers': dict(self.headers),
        }

# ################################################################################################################################
# ################################################################################################################################

class Request:
    """ Wraps a service request and adds some useful meta-data.
    """
    text: 'any_'

    __slots__ = ('service', 'logger', 'payload', 'text', 'input', 'cid', 'data_format', 'transport',
        'encrypt_func', 'encrypt_secrets', 'bytes_to_str_encoding', '_wsgi_environ', 'channel_params',
        'merge_channel_params', 'http', 'amqp', 'enforce_string_encoding')

    def __init__(
        self,
        service, # type: Service
        simple_io_config=None, # type: any_
        data_format=None, # type: strnone
        transport=None    # type: strnone
    ) -> 'None':
        self.service = service
        self.logger = cast_('Logger', None) # This is populated in a service's update_handle
        self.payload = ''
        self.text = ''
        self.input = None # type: any_
        self.cid = cast_('str', None)
        self.data_format = cast_('str', data_format)
        self.transport = cast_('str', transport)
        self.http = HTTPRequestData()
        self._wsgi_environ = cast_('stranydict', None)
        self.channel_params = cast_('stranydict', {})
        self.merge_channel_params = True
        self.amqp = cast_('AMQPRequestData', None)
        self.encrypt_func = None
        self.encrypt_secrets = True
        self.bytes_to_str_encoding = cast_('str', None)

# ################################################################################################################################

    def init(
        self,
        is_sio,       # type: bool
        cid,          # type: str
        sio,          # type: CySimpleIO
        data_format,  # type: str
        transport,    # type: str
        wsgi_environ, # type: stranydict
        encrypt_func  # type: callable_
    ) -> 'None':
        """ Initializes the object with an invocation-specific data.
        """
        self.input = ServiceInput()
        self.encrypt_func = encrypt_func

        if is_sio:

            parsed = sio.parse_input(self.payload or {}, data_format, extra=self.channel_params, service=self.service)

            if isinstance(parsed, Model):
                self.input = parsed
            else:
                if isinstance(parsed, dict):
                    self.input.update(parsed)
                for param, value in self.channel_params.items():
                    if param not in self.input:
                        self.input[param] = value

        # We merge channel params in if requested even if it's not SIO
        else:
            if self.merge_channel_params:
                self.input.update(self.channel_params)

# ################################################################################################################################

    @property
    def raw_request(self) -> 'any_':
        return self.text

# ################################################################################################################################

    @raw_request.setter
    def raw_request(self, value:'any_') -> 'any_':
        self.text = value

# ################################################################################################################################

    def to_bunch(self):
        """ Returns a bunchified (converted into bunch.Bunch) version of self.raw_request,
        deep copied if it's a dict (or a subclass). Note that it makes sense to use this method
        only with dicts or JSON input.
        """
        # We have a dict
        if isinstance(self.raw_request, dict):
            return bunchify(deepcopy(self.raw_request))

        # Must be a JSON input, raises exception when attempting to load it if it's not
        return bunchify(loads(self.raw_request))

    # Backward-compatibility
    bunchified = to_bunch

# ################################################################################################################################
# ################################################################################################################################
