# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# stdlib
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

# ################################################################################################################################
# ################################################################################################################################

local_tz_zone = 'Europe/Prague'

# ################################################################################################################################
# ################################################################################################################################

class ModuleCtx:
    Date_Format = '%Y-%m-%d'
    Date_Time_Format = '%Y-%m-%dT%H:%M:%S'
    Timestamp_Format = '%Y-%m-%dT%H:%M:%S.%f'

# ################################################################################################################################
# ################################################################################################################################

class TimeUtil:
    """ Date/time utilities for testing.
    Default format is always taken from ISO 8601 (so it's sorted lexicographically)
    and default timezone is always UTC.
    """

# ################################################################################################################################

    def now(self, format=ModuleCtx.Date_Time_Format, tz=local_tz_zone, needs_format=True, delta=None) -> 'str | datetime':
        """ Returns now in a specified timezone.
        """
        if tz == 'UTC':
            now = datetime.now(timezone.utc)
        else:
            now = datetime.now(ZoneInfo(tz))

        if delta:
            now = now + delta

        if needs_format:
            return now.strftime(format)

        return now

# ################################################################################################################################

    def _time_from(self, value, delta, format, needs_format):

        if isinstance(value, str):
            value = datetime.fromisoformat(value)

        value_from = value + timedelta(**delta)

        if needs_format:
            return value_from.strftime(format)
        else:
            return value_from

# ################################################################################################################################

    def one_day_from(self, date, format=ModuleCtx.Date_Format, needs_format=True):
        delta = {'days': 1}
        return self._time_from(date, delta, format, needs_format)

# ################################################################################################################################

    def one_hour_from(self, date, format=ModuleCtx.Date_Format, needs_format=True):
        delta = {'minutes': 60}
        return self._time_from(date, delta, format, needs_format)

# ################################################################################################################################

    def one_minute_from(self, date, format=ModuleCtx.Date_Format, needs_format=True):
        delta = {'minutes': 1}
        return self._time_from(date, delta, format, needs_format)

# ################################################################################################################################

    def yesterday(self, format=ModuleCtx.Date_Time_Format, tz=local_tz_zone, needs_format=True):
        return self.now(format, tz, needs_format, delta=timedelta(days=-1))

# ################################################################################################################################

    def tomorrow(self, format=ModuleCtx.Date_Time_Format, tz=local_tz_zone, needs_format=True):
        return self.now(format, tz, needs_format, delta=timedelta(days=1))

# ################################################################################################################################

    def utcnow(self, format=ModuleCtx.Date_Time_Format, needs_format=True) -> 'any_':
        """ Returns now in UTC formatted as given in 'format'.
        """
        return self.now(format, 'UTC', needs_format)

# ################################################################################################################################

    def utcnow_as_float(self, format=ModuleCtx.Date_Time_Format, needs_format=True) -> 'any_':
        """ Returns now in UTC as a float number.
        """
        return self.utcnow(needs_format=False).timestamp()

# ################################################################################################################################

    def today(self, format=ModuleCtx.Date_Format, tz=local_tz_zone, needs_format=True):
        """ Returns current day in a given timezone.
        """
        if tz == 'UTC':
            now = datetime.now(timezone.utc)
        else:
            now = datetime.now(ZoneInfo(tz))

        today = now.replace(hour=0, minute=0, second=0, microsecond=0)

        if needs_format:
            return today.strftime(format)
        else:
            return today

# ################################################################################################################################

    def isonow(self, tz=local_tz_zone, needs_format=True, _format=ModuleCtx.Timestamp_Format):
        return self.now(_format, tz, needs_format)

# ################################################################################################################################

    def isoutcnow(self, needs_format=True, _format=ModuleCtx.Timestamp_Format):
        return self.now(_format, 'UTC', needs_format)

# ################################################################################################################################

    def reformat(self, value, from_, to):
        """ Reformats value from one datetime format to another, for instance
        from 23-03-2013 to 03/23/13 (MM-DD-YYYY to DD/MM/YY).
        """
        try:
            parsed = datetime.strptime(str(value), from_)
            return parsed.strftime(to)
        except Exception:
            raise

# ################################################################################################################################
# ################################################################################################################################
