# -*- coding: utf-8 -*-

"""
Copyright (C) 2025, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.

This file is auto-generated by `make generate`. Do not edit manually.
"""

# stdlib
from datetime import date, datetime
from decimal import Decimal as decimal_
from pathlib import Path
from types import ModuleType
from typing import \
    Any as any_, \
    BinaryIO as binaryio_, \
    Callable as callable_, \
    cast as cast_, \
    Dict as dict_, \
    Generator as generator_, \
    Iterator as iterator_, \
    IO as io_, \
    NoReturn as noreturn, \
    List as list_, \
    Optional as optional, \
    Text as str_, \
    TextIO as textio_, \
    Tuple as tuple_, \
    Type as type_, \
    TypeVar as typevar_, \
    Set as set_, \
    Union as union_

try:
    from typing_extensions import TypeAlias as typealias_
except Exception:
    typealias_ = None

try:
    from typing import TypedDict, Protocol
except ImportError:
    TypedDict = None
    Protocol = None

from dataclasses import *

# ################################################################################################################################
# ################################################################################################################################

class BaseModel:
    pass

# ################################################################################################################################
# ################################################################################################################################


intnone       = optional[int]
strnone       = optional[str]

anydict       = dict_[any_, any_]
anydictnone   = optional[anydict]
anylist       = list_[any_]
anylistnone   = optional[anylist]
anynone       = optional[any_]
anyset        = set_[any_]
anytuple      = tuple_[any_, ...]
binaryio_     = binaryio_
boolnone      = optional[bool]
byteslist     = list_[bytes]
bytesnone     = optional[bytes]
callable_     = callable_[..., any_]
callnone      = optional[callable_]
cast_         = cast_
date_         = date
datetime_     = datetime
decimal_      = decimal_
decnone       = optional[decimal_]
dictlist      = list_[anydict]
dictnone      = optional[anydict]
dictorlist    = union_[anydict, anylist]
dtnone        = optional[datetime]
floatnone     = optional[float]
generator_    = generator_
intanydict    = dict_[int, any_]
intdict       = dict_[int, int]
intdictdict   = dict_[int, anydict]
intlist       = list_[int]
intlistempty  = list_[intnone]
intlistnone   = optional[list_[int]]
intset        = set_[int]
intsetdict    = dict_[int, anyset]
intstrdict    = dict_[int, str]
iterator_     = iterator_
iobytes_      = io_[bytes]
listnone      = anylistnone
listorstr     = union_[anylist, str]
listtuple     = tuple_[anylist, anylist]
model         = type_[BaseModel]
modelnone     = optional[type_[BaseModel]]
module_       = ModuleType
noreturn      = noreturn
path_         = Path
pathlist      = list_[path_]
set_          = set_
stranydict    = dict_[str, any_]
strcalldict   = dict_[str, callable_]
strdict       = stranydict
strbytes      = union_[str_, bytes]
strbooldict   = dict_[str, bool]
strdictdict   = dict_[str, anydict]
strdictlist   = list_[stranydict]
strdictnone   = union_[stranydict, None]
strint        = union_[str_, int]
strintbool    = union_[str_, int, bool]
strintdict    = dict_[str, int]
strintnone    = union_[strnone, intnone]
strlist       = list_[str]
strlistdict   = dict_[str, anylist]
strlistempty  = list_[strnone]
strlistnone   = optional[list_[str_]]
strordict     = union_[str, anydict]
strordictnone = union_[strnone, anydictnone]
strorfloat    = union_[str, float]
stroriter     = union_[str, anylist, anytuple]
strorlist     = listorstr
strorlistnone = optional[listorstr]
strset        = set_[str]
strsetdict    = dict_[str, anyset]
strstrdict    = dict_[str, str]
strtuple      = tuple_[str, ...]
textio_       = textio_
textionone    = textio_
tuple_        = tuple_
tuplist       = union_[anylist, anytuple]
tupnone       = optional[anytuple]
type_         = type_
typealias_    = typealias_
typevar_      = typevar_
union_        = union_

# ################################################################################################################################
# ################################################################################################################################

def instance_from_dict(class_:'any_', data:'anydict') -> 'any_':
    instance = class_()
    for key, value in data.items():
        setattr(instance, key, value)
    return instance

# ################################################################################################################################

def list_field() -> 'callable_[anylist]':
    return field(default_factory=list)

# ################################################################################################################################

def dict_field() -> 'callable_[anydict]':
    return field(default_factory=dict)

# ################################################################################################################################
# ################################################################################################################################
