
security:
  - name: postburn.globus.1.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.globus.1
    password: postburn.globus.1
  - name: postburn.orchestrator.1.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.orchestrator.1
    password: postburn.orchestrator.1
  - name: postburn.sentinel-2-l2a.1.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.sentinel-2-l2a.1
    password: postburn.sentinel-2-l2a.1
  - name: postburn.test.1.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.test.1
    password: postburn.test.1
  - name: postburn.test.2.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.test.2
    password: postburn.test.2
  - name: postburn.test.3.http.basic_auth
    is_active: True
    type: basic_auth
    username: postburn.test.3
    password: postburn.test.3

groups:

channel_rest:
  - name: pubsub.rest.get-messages
    service: pubsub.rest.get-messages
    url_path: /pubsub/messages/get
  - name: pubsub.rest.publish
    service: pubsub.rest.publish
    url_path: /pubsub/topic/{topic_name}
  - name: pubsub.rest.subscribe
    service: pubsub.rest.subscribe
    url_path: /pubsub/subscribe/topic/{topic_name}
  - name: pubsub.rest.unsubscribe
    service: pubsub.rest.unsubscribe
    url_path: /pubsub/unsubscribe/topic/{topic_name}

outgoing_rest:

scheduler:
  - name: zato.outgoing.sql.auto-ping
    is_active: True
    service: zato.outgoing.sql.auto-ping
    job_type: interval_based
    start_date: 2026-03-31 14:10:33
    minutes: 3

ldap:
sql:
outgoing_soap:
microsoft_365:
cache:
confluence:
jira:
email_imap:
email_smtp:
odoo:
elastic_search:

pubsub_topic:
  - name: postburn.globus.1
  - name: postburn.orchestrator.1
  - name: postburn.sentinel-2-l2a.1
  - name: postburntest
  - name: postburntest2

pubsub_permission:
  - security: postburn.globus.1.http.basic_auth
    pub:
      - postburn.orchestrator.1
    sub:
      - postburn.globus.1
  - security: postburn.orchestrator.1.http.basic_auth
    pub:
      - postburn.sentinel-2-l2a.1
    sub:
      - postburn.orchestrator.1
  - security: postburn.sentinel-2-l2a.1.http.basic_auth
    pub:
      - postburn.orchestrator.1
    sub:
      - postburn.sentinel-2-l2a.1
  - security: postburn.test.1.http.basic_auth
    pub:
      - postburn.sentinel-2-l2a.1
      - postburntest
  - security: postburn.test.2.http.basic_auth
    sub:
      - postburn.sentinel-2-l2a.1
      - postburntest
  - security: postburn.test.3.http.basic_auth
    pub:
      - postburntest2

pubsub_subscription:
  - security: postburn.sentinel-2-l2a.1.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburn.orchestrator.1
      - postburn.sentinel-2-l2a.1
  - security: postburn.orchestrator.1.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburn.orchestrator.1
      - postburn.sentinel-2-l2a.1
  - security: postburn.test.2.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburn.sentinel-2-l2a.1
      - postburntest
  - security: postburn.test.1.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburn.sentinel-2-l2a.1
      - postburntest
  - security: postburn.globus.1.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburn.globus.1
      - postburn.orchestrator.1
  - security: postburn.test.3.http.basic_auth
    delivery_type: pull
    topic_list:
      - postburntest2

channel_openapi:
